### ISSUE TITLE
Proměnné pojmenovávat velkými písmeny, jen jde-li o nějakou matematickou / fyzikální veličinu

### ISSUE THREAD

**Issue by xtompok** [cernickyd/du1_david_cernicky#3]

**Comment by cernickyd** [comment]
Budu se snažit :)  
Něco jsem opravil, ale "R" jsem tak ponechal (obecně je to konstanta).

**Comment by xtompok** [comment]
R je v pořádku, ještě Ti tam zbyly Rovnobezky a Poledniky, ale to očekávám opravíš spolu s #6
