### ISSUE TITLE
While cyklus u výběru zobrazení nepotřebuje proměnnou I

### ISSUE THREAD

**Issue by xtompok** [cernickyd/du1_david_cernicky#4]
Ukazovali jsme si, jak napsat while cyklus tak, aby potřeboval jen tu proměnnou, kterou se snaží získat od uživatele, použití `I` je nadbytečné

**Comment by cernickyd** [comment]
S tím jsem pracoval na začátku, zapomněl jsem to tam. Díky za připomenutí.
